/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : PC_M1.H
**     Project   : DSPC51
**     Processor : 56F8037
**     Beantype  : PC_Master
**     Version   : Bean 01.032, Driver 01.13, CPU db: 2.87.237
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 2011-2-23, ÏÂÎç 01:51
**     Abstract  :
**          The PC master software application is a software tool initially created
**          for developers of Motor Control applications but it may be extended to any
**          application development. This tool allows control of an application remotely
**          from a user-friendly graphical environment running on a PC.
**     Comment   :
**         8030
**     Settings  :
**          AsynchroSerial                       : Inhr7
**
**          Initialization:
**              Recorder buffer length           : 512
**              Command buffer length            : 4
**              Data buffer size                 : 128
**              Recorder timebase                : 32816
**              Board firmware major number      : 5
**              Board firmware minor number      : 0
**              Device identification string     : PC Master communication !
**     Contents  :
**         pcmasterdrvInit     - Word16 PC_M1_pcmasterdrvInit(sPCMasterComm *p_sPCMasterComm);
**         pcmasterdrvIsr      - void PC_M1_pcmasterdrvIsr(void);
**         pcmasterdrvRecorder - void pcmaster_record(void);
**
**     (c) Freescale Semiconductor
**     2004 All Rights Reserved
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2006
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

#ifndef __PC_M1
#define __PC_M1
/* Standard ANSI C types */

/*
** ===================================================================
**     Method      :  pcmaster_record (bean PC_Master)
**
**     Description :
**         Recorder Routine. It performs sampling of data into
**         buffer which is located on the address p_recBuff item is
**         pointing and its length is determined by recSize item in
**         the initialization structure of sPCMasterComm type.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#include <stdint.h>

void pcmaster_record(void);
void pcmaster_write(const char * buffer, int offset, int length);
void pcmaster_init(void (*call_back)(const char *, int));

#endif /* ifndef __PC_M1 */
